site_name: SmartDNS
site_description: SmartDNS
site_author: pymumu
repo_name: 'pymumu/smartdns'
repo_url: 'https://github.com/pymumu/smartdns'

# Copyright
copyright: "Copyright &copy; Nick Peng"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github 
  logo: assets/smartdns.png
  feature:
    tabs: true
  favicon: 'assets/smartdns.png'
  language: 'en'
  include_sidebar: false
  palette:
    - scheme: default
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: 'dark'
      accent: 'dark'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.path
    - navigation.prune
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.code.copy

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  alternate:
    - name: 中文
      link: ./ ..
      lang: zh
    - name: English
      link: ./ 
      lang: en

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


nav:
  - Home: 'index.md'
  - Download: 'download.md'
  - Installation: 
    - Linux: 'install/linux.md'
    - OpenWrt: 'install/openwrt.md'
    - ASUS firmware / Merlin firmware: 'install/asus.md'
    - EntWare: 'install/entware.md'
    - WSL: 'install/wsl.md'
    - Docker: 'install/docker.md'
  - Configuration Guides:
    - Basic Configuration: 'config/basic-config.md'
    - Server Configuration: 'config/server-config.md'
    - Cache Settings: 'config/cache.md'
    - Ad Blocking: 'config/ad-block.md'
    - Dual Stack Optimization: 'config/dualstack.md'
    - Disable IPV6: 'config/block-ipv6.md'
    - Domain Forwarding: 'config/domain-forwarding.md'
    - Check Speed Mode: 'config/check-speed-mode.md'
    - Domain Rules: 'config/domain-rule.md'
    - Client Rules: 'config/client-rule.md'
    - Domain Address: 'config/domain-address.md'
    - CNAME Alias Query: 'config/cname.md'
    - Domain Set: 'config/domain-set.md'
    - IPSet and NFTSet: 'config/ipset-nftset.md'
    - Query through Proxy: 'config/proxy.md'
    - DNS64: 'config/dns64.md'
    - IP Rule: 'config/ip-rule.md'
    - IP Set: 'config/ip-set.md'
    - IP Alias: 'config/ip-alias.md'
    - Security Related: 'config/security.md'
    - Forwarding with IPSet: 'config/forwarding-with-ipset.md'
    - Edns Client Subnet: 'config/edns-client-subnet.md'
    - Bootstrap DNS: 'config/bootstrap-dns.md'
    - Resolve Local Hostname: 'config/resolv-dnsmasq-lease.md'
  - Configurations: 'configuration.md'
  - Compile: 'compile.md'
  - FAQ: 'faq.md'
  - Donate: 'donate.md'